<?php
namespace common\models\mysql;

class DistributionModel extends ActiveRecord
{

    public static function tableName()
    {
        return "{{%base_list}}";
    }

    public function beforeSave($insert)
    {
        $sn = $this->sn;
        $this->setAttribute('sn',trim($sn));

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}