<?php
namespace common\models\mysql;

class PhoneModel extends ActiveRecord
{

    public static function tableName()
    {
        return "{{%phone}}";
    }

    public function getBrand(){
        return $this->hasOne(BrandModel::className(), ['id' => 'brand_id'])
            ->select(['id','name','barcode']);
    }

    public function beforeSave($insert)
    {
        $this->status = 0;
        if($this->width <= 0 or $this->height <= 0) $this->status = 2;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}