<?php
namespace common\models\mysql;

class ThemeModel extends ActiveRecord
{
    const THEME_TYPE_NONE = 0; //ÎŞ²à±ßËØ²Ä
    const THEME_TYPE_LEFT = 1; //µ¥×ó²à±ß
    const THEME_TYPE_RIGHT = 2; //µ¥ÓÒ²à±ß
    const THEME_TYPE_DOUBLE = 3; //Ë«²à±ß

    public static function tableName()
    {
        return "{{%theme}}";
    }

    public function getCustomer(){
        return $this->hasOne(CustomerModel::className(), ['id' => 'customer_id'])
            ->select(['id','name']);
    }

    public function beforeSave($insert)
    {
        $this->status = 0;
        $this->template_url = trim($this->template_url);
        $this->left_template_url = trim($this->left_template_url);
        $this->right_template_url = trim($this->right_template_url);
        if(!$this->template_url) $this->status = 2;
        if($this->type == static::THEME_TYPE_LEFT and !$this->left_template_url) $this->status = 2;
        if($this->type == static::THEME_TYPE_RIGHT and !$this->right_template_url) $this->status = 2;
        if($this->type == static::THEME_TYPE_DOUBLE
            and (!$this->left_template_url or !$this->right_template_url)
        ) $this->status = 2;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}